name: Update FTP Secret
on:
  workflow_dispatch:

jobs:
  test-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Test FTP connection to studiologos.com.br
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: studiologos.com.br
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /tmp/
          server-dir: /
          dry-run: true
          protocol: ftps
          port: 21
          timeout: 30000

      - name: Test FTP connection to ftp.studiologos.com.br
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.studiologos.com.br
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /tmp/
          server-dir: /
          dry-run: true
          protocol: ftps
          port: 21
          timeout: 30000
